version: '3.9'

services:

  authorization-service:
    image: ghcr.io/ingsis25/authorization-service:prod
    container_name: authorization-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL_AUTHDB}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME_AUTHDB}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD_AUTHDB}
    depends_on:
      - auth-db
  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    ports:
      - "5432:5432"


  snippet-service:
    image: ghcr.io/ingsis25/snippet-service:prod
    container_name: snippet-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL_SNIPPET}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME_SNIPPET}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD_SNIPPET}
    depends_on:
      - snippet-db

  snippet-db:
    image: postgres:15
    container_name: snippet-db
    environment:
      POSTGRES_DB: snippetdb
      POSTGRES_USER: snippetuser
      POSTGRES_PASSWORD: snippetpass
    ports:
      - "5433:5432"


  runner-service:
    image: ghcr.io/ingsis25/runner-service:prod
    container_name: runner-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL_RUNNER}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME_RUNNER}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD_RUNNER}
    depends_on:
      - runner-db

  runner-db:
    image: postgres:15
    container_name: runner-db
    environment:
      POSTGRES_DB: runnerdb
      POSTGRES_USER: runneruser
      POSTGRES_PASSWORD: runnerpass
    ports:
      - "5434:5432"

networks:
  default:
    driver: bridge
