name: "Continuous Deployment Dev"

on:
  push:
    branches:
      - dev

jobs:
  deploy_to_vm:
    runs-on: ubuntu-latest
    steps:
      - name: Determine service
        id: service
        run: |
          echo "REPO_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV
          echo "CHANGED_SERVICE=$REPO_NAME" >> $GITHUB_ENV

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST_DEV }}
          username: ${{ secrets.VM_USER_DEV }}
          key: ${{ secrets.VM_KEY_DEV }}
          script: |
            cd infra
            git pull origin dev

            # Login a GHCR como root para usar sudo docker
            echo ${{ secrets.GITHUB_TOKEN }} | sudo -i docker login -u ${{ github.actor }} --password-stdin ghcr.io

    
            if [ "${CHANGED_SERVICE}" = "infra" ]; then
              sudo docker-compose -f docker-compose.dev.yml down
              sudo docker-compose -f docker-compose.dev.yml pull
              sudo docker-compose -f docker-compose.dev.yml up -d
            else
              sudo docker-compose -f docker-compose.dev.yml pull ${CHANGED_SERVICE}-service
              sudo docker-compose -f docker-compose.dev.yml up -d ${CHANGED_SERVICE}-service
            fi
