name: "Continuous Deployment"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy_to_vm:
    runs-on: ubuntu-latest

    steps:
      - name: Determine service
        id: service
        run: |
          echo "REPO_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV
          echo "CHANGED_SERVICE=$REPO_NAME" >> $GITHUB_ENV

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST_PROD }}
          username: ${{ secrets.VM_USER_PROD }}
          key: ${{ secrets.VM_KEY_PROD }}

          envs: CHANGED_SERVICE

          script: |
            cd infra
            git pull origin main

            echo ${{ secrets.GHCR_PAT }} | sudo -i docker login -u ${{ github.actor }} --password-stdin ghcr.io

            if [ -z "${CHANGED_SERVICE}" ] || [ "${CHANGED_SERVICE}" = "infra" ]; then
              echo "Redeploy completo de infra"
              sudo docker compose -f docker-compose.prod.yml down
              sudo docker compose -f docker-compose.prod.yml pull
              sudo docker compose -f docker-compose.prod.yml up -d
            else
              echo "Redeploy solo de ${CHANGED_SERVICE}-service"
              sudo docker compose -f docker-compose.prod.yml pull "${CHANGED_SERVICE}-service"
              sudo docker compose -f docker-compose.prod.yml up -d "${CHANGED_SERVICE}-service"
            fi
